Repository eclipse-edc/Technology-Aws, pull requests merged in 2024-03, with the labels that each got.

#256 fix: adapt to EDC upstream
  DEPENDENCIES
  extensions/control-plane/provision/provision-aws-s3/src/main/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGenerator.java
  extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGeneratorTest.java
Labels: bug

#267 fix: compilation
  DEPENDENCIES
  extensions/control-plane/provision/provision-aws-s3/src/test/java/org/eclipse/edc/connector/provision/aws/s3/S3ConsumerResourceDefinitionGeneratorTest.java
Labels: bug

#273 fix: use http-lib to get HttpTestUtils
  DEPENDENCIES
  extensions/common/aws/aws-s3-test/build.gradle.kts
  extensions/common/aws/aws-s3-test/src/testFixtures/java/org/eclipse/edc/aws/s3/testfixtures/S3TestClient.java
  gradle/libs.versions.toml
Labels: bug, breaking-change

#275 build: fix compilation
  DEPENDENCIES
  build.gradle.kts
  extensions/common/vault/vault-aws/build.gradle.kts
  extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/DataPlaneS3ExtensionTest.java
  gradle.properties
  gradle/libs.versions.toml
Labels: build
