Repository eclipse-edc/Technology-Aws, pull requests merged in 2024-01, with the labels that each got.

#191 build: bump gradle-wrapper to 8.5
  DEPENDENCIES
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#195 fix: compile errors after EDC token refactor
  DEPENDENCIES
  extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtension.java
  extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtensionTest.java
Labels: bug

#198 build: make trigger_snapshot workflow manually triggerable
  .github/ISSUE_TEMPLATE/adoption_request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/bump-version/action.yml
  .github/actions/run-tests/action.yml
  .github/actions/setup-build/action.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-tech-aws.yml
  .github/workflows/trigger_snapshot.yml
  .github/workflows/verify.yaml
Labels: enhancement
