Repository eclipse-edc/Technology-Aws, pull requests merged in 2024-12, with the labels that each got.

#485 feat: allow endpoint overrides in AwsSecretsManagerVault
  extensions/common/vault/vault-aws/build.gradle.kts
  extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtension.java
  extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultExtensionTest.java
Labels: enhancement

#503 docs: add required AWS permissions to data plane README
  extensions/data-plane/data-plane-aws-s3/README.md
Labels: documentation

#502 build: cleanup unused dependencies
  gradle/libs.versions.toml
Labels: dependencies, build
