Repository eclipse-edc/Technology-Aws, pull requests merged in 2024-08, with the labels that each got.

#402 fix(ci): set version before tests, publishing
  .github/workflows/publish.yaml
  .github/workflows/release-tech-aws.yml
  .github/workflows/verify.yaml
  DEPENDENCIES
Labels: bug, build

#403 chore: reset dependencies to 0.7.1 to avoid build errors
  .github/workflows/publish.yaml
  .github/workflows/release-tech-aws.yml
  .github/workflows/verify.yaml
  DEPENDENCIES
  gradle.properties
  gradle/libs.versions.toml
Labels: bug, build

#409 build: prepare bugfix/0.7.2 release
  .github/workflows/prepare-release.yml
  .github/workflows/publish.yaml
  .github/workflows/release.yml
  .github/workflows/test-repo-split.yaml
  DEPENDENCIES
  gradle/libs.versions.toml
Labels: build

#417 fix(s3 dataplane): Fix transfer of empty objects
  DEPENDENCIES
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSink.java
  extensions/data-plane/data-plane-aws-s3/src/main/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSource.java
  extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataPlaneIntegrationTest.java
  extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkTest.java
Labels: bug

#422 ci: launch test workflow also on release and bugfix branches
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-check.yml
  .github/workflows/nightly.yaml
  .github/workflows/release-tech-aws.yml
  .github/workflows/verify.yaml
Labels: build
