Repository eclipse-edc/Technology-Aws, pull requests merged in 2024-07, with the labels that each got.

#364 chore: Bump version
  DEPENDENCIES
  extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSinkTest.java
  extensions/data-plane/data-plane-aws-s3/src/test/java/org/eclipse/edc/connector/dataplane/aws/s3/S3DataSourceTest.java
  gradle.properties
  gradle/libs.versions.toml
Labels: bug

#381 chore(deps): bump to latest EDC
  DEPENDENCIES
  gradle/libs.versions.toml
Labels: bug, dependencies

#379 feat: Modifies the AWS vault implementation to update existing secrets
  extensions/common/vault/vault-aws/src/main/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVault.java
  extensions/common/vault/vault-aws/src/test/java/org/eclipse/edc/vault/aws/AwsSecretsManagerVaultTest.java
Labels: enhancement

#382 feat(ci): create tag and merge commit manually
  .github/workflows/release-tech-aws.yml
  DEPENDENCIES
Labels: enhancement, build
